# Generated by Django 5.1.1 on 2024-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_rename_state_listing_region_listing_lot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('apartment', 'Apartment'), ('Townhouse', 'Townhouse'), ('office_space', 'Office Space')], default='House', max_length=1000),
        ),
    ]
