# Generated by Django 5.1.1 on 2024-09-23 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_useraccount_address_useraccount_captcha_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="address",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="captcha_score",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="country",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="has_profile",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="post_code",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="town",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="updated",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Town/City"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Post Code"
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Latitude"
                    ),
                ),
                ("captcha_score", models.FloatField(default=0.0)),
                ("has_profile", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
