# Generated by Django 5.1.1 on 2024-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
