# Generated by Django 5.1.1 on 2024-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default-profile-pic.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
